server:
  port:  8080
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kss_db
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: kssambalaj@gmail.com
    password: yguawliavqandllp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      '[hibernate.format_sql]': true
  #image
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  profiles:
    active: dev

logging:
  file:
    name: log/kssambalaj.log
  pattern:
    file: "%d %-5level [%thread]  %logger:%msg%n"
  level:
    '[org.springframework.web]': WARN
    '[org.hibernate]': INFO
    '[org.kssambalaj]': DEBUG

management: #actuator
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled:  true

kssambalaj:
  app:
    jwtSecret: GamingProMarket200323binaryBeastsGpMeCommerceOaIsReTaSaOzYuBe
    jwtExpirationMS: 86400000
    mailAddress: kssambalaj@gmail.com
    backendLink: https://ecommerce-backend-v2.herokuapp.com/
    resetPasswordLink: http://localhost:3000/

info:
  application:
    name: 'KSS Ambalaj Backend App'
    description: 'This is KSS Ambalaj E-Commerce Backend Project'
    version: '@project.version@'
